baseURL: "https://backtobasicsepita.github.io"
languageCode: "fr-fr"
title: "B2B - TPs de programmation"
theme: "PaperMod"

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  DateFormat: "2 January 2006"
  defaultTheme: auto # dark, light
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  profileMode:
    enabled: true # needs to be explicitly set
    title: BackToBasics
    subtitle: "Sujets de révision de programmations écrits par les membres BackToBasics"
    imageUrl: "B2B_logo.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "logo backtobasics"
    buttons:
      - name: "Sujets B1"
        url: b1
      - name: "Sujets B2"
        url: b2
      - name: "Sujets B3"
        url: b3

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    
menu:
  main:
    - identifier: b1
      name: "Sujets B1"
      url: b1
      weight: 5
    - identifier: b2
      name: "Sujets B2"
      url: b2
      weight: 10
    - identifier: b3
      name: "Sujets B3"
      url: b3
      weight: 10
